/**
 * Sample consultation pipeline — the commercial side of the dashboard.
 *
 * Every organisation, person and figure below is invented for demonstration. None of
 * it describes a real Ample Care lead or client. Example addresses use the reserved
 * `.example` domain so nothing here can accidentally reach a real inbox.
 *
 * Kept separate from `mockData.ts` because leads arrive from the public website and
 * will be the first thing replaced by a real backend — a form endpoint writing to a
 * database. Delete this file at that point rather than editing it.
 */
import type { Consultation, ConsultationEvent, EnquiryNote } from '@/lib/admin/types';

export const consultations: Consultation[] = [
  {
    id: 'lead-5001',
    organisationName: 'Brambleside Nursing Home',
    organisationType: 'nursing_home',
    staffCount: 96,
    enquirerName: 'Dawn Whitfield',
    enquirerRole: 'Registered Manager',
    email: 'd.whitfield@brambleside.example',
    phone: '0161 496 0142',
    challenges: ['burnout', 'absence'],
    preferredContact: 'phone',
    availability: 'Weekday mornings before 10am, after handover',
    notes:
      'Two senior carers left in the same month. The night team is covering gaps with overtime and the deputy is worried about the knock-on effect.',
    stage: 'new_enquiry',
    owner: 'Naomi Price',
    submittedAt: '2026-08-11T07:42:00.000Z',
    nextActionAt: '2026-08-12T09:00:00.000Z',
    nextAction: 'Call to book the free consultation',
    packageInterest: 'undecided',
  },
  {
    id: 'lead-5002',
    organisationName: 'Kingsmead Supported Living',
    organisationType: 'supported_living',
    staffCount: 42,
    enquirerName: 'Marcus Ellery',
    enquirerRole: 'Service Director',
    email: 'm.ellery@kingsmead.example',
    phone: '0117 402 8890',
    challenges: ['engagement', 'workload'],
    preferredContact: 'email',
    availability: 'Tuesdays and Thursdays, any time',
    notes: 'Wants to understand what staff actually get out of the assessment before committing.',
    stage: 'company_registered',
    owner: 'Naomi Price',
    submittedAt: '2026-08-06T14:20:00.000Z',
    consultationAt: '2026-08-14T10:30:00.000Z',
    nextActionAt: '2026-08-13T16:00:00.000Z',
    nextAction: 'Prepare tailored pack ahead of the call',
    packageInterest: 'assessment',
  },
  {
    id: 'lead-5003',
    organisationName: 'Ravensmoor Domiciliary Care',
    organisationType: 'domiciliary',
    staffCount: 210,
    enquirerName: 'Priya Raman',
    enquirerRole: 'Operations Director',
    email: 'p.raman@ravensmoor.example',
    phone: '0113 887 3311',
    challenges: ['stress', 'absence', 'workload'],
    preferredContact: 'phone',
    availability: 'Late afternoons from 4pm',
    notes:
      'Large round-based workforce across three regions. Travel time and lone working are the recurring themes raised by supervisors.',
    stage: 'report_reviewed',
    owner: 'Elliot Mensah',
    submittedAt: '2026-07-29T09:05:00.000Z',
    consultationAt: '2026-08-05T16:30:00.000Z',
    nextActionAt: '2026-08-12T12:00:00.000Z',
    nextAction: 'Send indicative pricing for 210 staff',
    packageInterest: 'assessment_plan',
  },
  {
    id: 'lead-5004',
    organisationName: 'Fairhaven Court Care Home',
    organisationType: 'care_home',
    staffCount: 64,
    enquirerName: 'Tom Ashby',
    enquirerRole: 'Registered Manager',
    email: 't.ashby@fairhaven.example',
    phone: '0191 330 5578',
    challenges: ['burnout', 'mental_health'],
    preferredContact: 'email',
    availability: 'Any weekday afternoon',
    notes:
      'Inspection action plan references staff wellbeing. Needs something demonstrable before the next visit.',
    stage: 'proposal_sent',
    owner: 'Naomi Price',
    submittedAt: '2026-07-18T11:15:00.000Z',
    consultationAt: '2026-07-24T14:00:00.000Z',
    nextActionAt: '2026-08-12T10:00:00.000Z',
    nextAction: 'Chase proposal — sent 8 days ago, no reply',
    packageInterest: 'ongoing',
  },
  {
    id: 'lead-5005',
    organisationName: 'Harbour Oaks Care Home',
    organisationType: 'care_home',
    staffCount: 148,
    enquirerName: 'Leanne Cooper',
    enquirerRole: 'Registered Manager',
    email: 'l.cooper@harbouroaks.example',
    phone: '0333 577 2070',
    challenges: ['absence', 'burnout'],
    preferredContact: 'phone',
    availability: 'Mondays and Fridays',
    notes: 'Converted after the February consultation. Now an active delivery account.',
    stage: 'confirmed_client',
    owner: 'Naomi Price',
    submittedAt: '2026-02-03T10:00:00.000Z',
    consultationAt: '2026-02-10T11:00:00.000Z',
    packageInterest: 'ongoing',
    companyId: 'harbour-oaks',
  },
  {
    id: 'lead-5006',
    organisationName: 'Ashcombe Lodge',
    organisationType: 'care_home',
    staffCount: 28,
    enquirerName: 'Grace Ndlovu',
    enquirerRole: 'Owner',
    email: 'g.ndlovu@ashcombe.example',
    phone: '01452 776 210',
    challenges: ['engagement'],
    preferredContact: 'email',
    availability: 'Flexible',
    notes: 'Budget deferred to the next financial year. Worth revisiting in April.',
    stage: 'closed_lost',
    owner: 'Elliot Mensah',
    submittedAt: '2026-06-11T13:30:00.000Z',
    consultationAt: '2026-06-18T09:30:00.000Z',
    packageInterest: 'assessment',
    lostReason: 'Budget deferred to next financial year — revisit April 2027',
  },

  /* Engagements for the three existing delivery accounts, so every company
     workspace has a stage rather than showing "no engagement record". */
  {
    id: 'lead-5007',
    organisationName: 'Meadow Bridge Domiciliary',
    organisationType: 'domiciliary',
    staffCount: 96,
    enquirerName: 'Sadia Rahman',
    enquirerRole: 'Registered Manager',
    email: 's.rahman@meadowbridge.example',
    phone: '0161 224 8890',
    challenges: ['absence', 'workload'],
    preferredContact: 'email',
    availability: 'Weekday afternoons',
    notes: 'Survey issued to 96 staff. Participation is lagging on the North Patch round.',
    stage: 'survey_in_progress',
    owner: 'Elliot Mensah',
    submittedAt: '2026-07-20T09:00:00.000Z',
    nextActionAt: '2026-08-13T09:00:00.000Z',
    nextAction: 'Chase participation — 32% with a week to close',
    packageInterest: 'assessment_plan',
    companyId: 'meadow-bridge',
  },
  {
    id: 'lead-5008',
    organisationName: 'Cedar View Supported Living',
    organisationType: 'supported_living',
    staffCount: 62,
    enquirerName: 'Owen Baptiste',
    enquirerRole: 'Service Manager',
    email: 'o.baptiste@cedarview.example',
    phone: '0121 668 4410',
    challenges: ['engagement', 'stress'],
    preferredContact: 'email',
    availability: 'Mornings',
    notes: 'Survey link sent 9 August. Only four responses so far — needs a reminder.',
    stage: 'survey_link_sent',
    owner: 'Naomi Price',
    submittedAt: '2026-08-01T10:30:00.000Z',
    nextActionAt: '2026-08-14T09:00:00.000Z',
    nextAction: 'Ask Owen to re-share the link at team meeting',
    packageInterest: 'assessment',
    companyId: 'cedar-view',
  },
  {
    id: 'lead-5009',
    organisationName: 'Willow Ward Nursing',
    organisationType: 'nursing_home',
    staffCount: 74,
    enquirerName: 'Jean Fairbairn',
    enquirerRole: 'Registered Manager',
    email: 'j.fairbairn@willowward.example',
    phone: '0131 552 7719',
    challenges: ['burnout', 'mental_health'],
    preferredContact: 'phone',
    availability: 'Wednesdays',
    notes: 'Account set up. Survey drafted but not yet issued to staff.',
    stage: 'company_registered',
    owner: 'Elliot Mensah',
    submittedAt: '2026-08-04T13:45:00.000Z',
    nextActionAt: '2026-08-12T09:00:00.000Z',
    nextAction: 'Issue the survey link to Jean',
    packageInterest: 'undecided',
    companyId: 'willow-ward',
  },
];

export const consultationEvents: ConsultationEvent[] = [
  {
    id: 'lev-1',
    consultationId: 'lead-5003',
    at: '2026-07-29T09:05:00.000Z',
    actor: 'Website',
    action: 'Enquiry received',
    detail: 'Consultation request submitted through the website form.',
  },
  {
    id: 'lev-2',
    consultationId: 'lead-5003',
    at: '2026-07-30T10:12:00.000Z',
    actor: 'Elliot Mensah',
    action: 'Moved to Consultation booked',
    detail: 'Call agreed for 5 August, 4:30pm.',
  },
  {
    id: 'lev-3',
    consultationId: 'lead-5003',
    at: '2026-08-05T17:20:00.000Z',
    actor: 'Elliot Mensah',
    action: 'Moved to Contacted',
    detail: 'Consultation held. Travel time and lone working confirmed as the priority themes.',
  },
  {
    id: 'lev-4',
    consultationId: 'lead-5004',
    at: '2026-07-18T11:15:00.000Z',
    actor: 'Website',
    action: 'Enquiry received',
    detail: 'Consultation request submitted through the website form.',
  },
  {
    id: 'lev-5',
    consultationId: 'lead-5004',
    at: '2026-08-04T09:40:00.000Z',
    actor: 'Naomi Price',
    action: 'Moved to Proposal sent',
    detail: 'Proposal issued for 64 staff on the ongoing support package.',
  },
];

export const enquiryNotes: EnquiryNote[] = [
  {
    id: 'en-1',
    enquiryId: 'enq-9001',
    createdAt: '2026-08-09T15:10:00.000Z',
    author: 'Naomi Price',
    content: 'Spoke with the deputy manager. Night team rota is the recurring pressure point.',
  },
  {
    id: 'en-2',
    enquiryId: 'enq-9001',
    createdAt: '2026-08-10T09:25:00.000Z',
    author: 'Elliot Mensah',
    content: 'Manager has agreed to protected breaks on nights from the next rota cycle.',
  },
];
